import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '../components/Navbar'
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="bg-gray-100 overflow-x-hidden overflow-y-auto">
        {/* Navbar */}
        <Navbar />

        {/* Conteúdo da página */}
      <main className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-screen-xl py-6 overflow-visible">{children}</main>
      <Toaster />
      </body>
    </html>
  );
}
